### PR TITLE
fix path and URL HttpServlet according to spec.

### LINKED ISSUE #1787: io.opencensus.contrib.http.servlet.OcHttpServletExtractor#getPath allways return null when using with spring
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.19.2

### What JVM are you using (`java -version`)?
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.
Say we build an application with spring boot. An endpoint mapping to "/test". 
Please have a visit to my very simple demo (https://github.com/KarlManong/opencensus-demo).

### What did you expect to see?
except "/test"

### What did you see instead?
Once we request the endpoint, `io.opencensus.contrib.http.servlet.OcHttpServletExtractor#getPath` return `null`

### PR DESCRIPTION
**Pull request by rghetia**
fixes #1787

### CODE REVIEW

File: contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletExtractor.java [hunk 1]
```diff
@@ -39,7 +39,10 @@ public String getMethod(HttpServletRequest request) {
 
   @Override
   public String getPath(HttpServletRequest request) {
-    return request.getPathInfo();
+    // Path defined in the <a
+    // href="https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/HTTP.md#attributes>spec</a>
```
Comment (songy23) [inline contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletExtractor.java]: nit: you don't need to include href in the comments.

File: contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletExtractor.java [hunk 2]
```diff
@@ -57,7 +60,10 @@ public int getStatusCode(@Nullable HttpServletResponse response) {
 
   @Override
   public String getUrl(HttpServletRequest request) {
-    return request.getRequestURL().toString();
+    // Url defined in the <a
+    // href="https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/HTTP.md#attributes">spec</a>
```
Comment (songy23) [inline contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletExtractor.java]: same here
