### PR TITLE
fix: Shutdown Stackdriver MetricServiceClient properly

### LINKED ISSUE #2007: StackdriverStatsExporter does not shut down the MetricServiceClient
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
`"io.opencensus" % "opencensus-exporter-stats-stackdriver" % "0.24.0"`

### What JVM are you using (`java -version`)?
```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

### What did you do?

```
StackdriverStatsExporter.createAndRegister()
StackdriverStatsExporter.unregister()
StackdriverStatsExporter.createAndRegister()
```

The issue is that `unregister` doesn't clean up the resources it allocates though. The code above just demonstrates it.

### What did you expect to see?

No exceptions

### What did you see instead?

```
Feb 07, 2020 9:27:18 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=17, target=monitoring.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:512)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:268)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:185)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:177)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:155)
	at com.google.cloud.monitoring.v3.stub.GrpcMetricServiceStub.create(GrpcMetricServiceStub.java:176)
	at com.google.cloud.monitoring.v3.stub.MetricServiceStubSettings.createStub(MetricServiceStubSettings.java:187)
	at com.google.cloud.monitoring.v3.MetricServiceClient.<init>(MetricServiceClient.java:157)
	at com.google.cloud.monitoring.v3.MetricServiceClient.create(MetricServiceClient.java:138)
	at io.opencensus.exporter.stats.stackdriver.StackdriverStatsExporter.createMetricServiceClient(StackdriverStatsExporter.java:422)
	at io.opencensus.exporter.stats.stackdriver.StackdriverStatsExporter.createInternal(StackdriverStatsExporter.java:388)
	at io.opencensus.exporter.stats.stackdriver.StackdriverStatsExporter.createAndRegister(StackdriverStatsExporter.java:221)
```

### Additional context

The issue is that `StackdriverStatsExporter` allocates a `MetricServiceClient`, but fails to invoke `client.shutdown` or `client.shutdownNow` on `StackdriverStatsExporter.unregister()`

### PR DESCRIPTION
**Pull request by janhicken**
Using the default configuration of `StackdriverStatsConfiguration`, a `MetricServiceClient` is initialized by the `StackdriverStatsExporter`.

This client was never closed, this will be done now when the `StackdriverStatsExporter.unregister()` method is called.

If a custom `MetricServiceStub` is given by the user, it will *not* be closed as the user should be in charge of it.

This should fix #2007.

### CODE REVIEW

File: exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java [hunk 1]
```diff
@@ -392,10 +396,13 @@ private static void createInternal(
       throws IOException {
     synchronized (monitor) {
       checkState(instance == null, "Stackdriver stats exporter is already created.");
-      MetricServiceClient client =
-          stub == null
-              ? createMetricServiceClient(credentials, deadline)
-              : MetricServiceClient.create(stub);
+      final MetricServiceClient client;
```
Comment (punya) [inline exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java:399]: How about saving the `MetricServiceClient` in both cases (stub as well as real)? Closing the stub client seems innocuous.

Comment (janhicken) [reply exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java:399]: I thought about that as well. 

However, if the user configures a stub they also use in another place too, the behavior could be very surprising. I like the pattern, where the piece of code creating the client will be responsible for closing it, too. Closing the given client would violate that pattern.

**Review by punya — APPROVED** [review]
